[project]
name = "aoc2024"
version = "0.1.0"
description = "Advent of Code 2024"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.1.3",
    "scanf>=1.5.2",
    "scipy>=1.14.1",
]

[tool.uv.workspace]
members = ["aoc2024"]

[tool.black]
line-length = 110
